## Enums used by the editor interface access system.
@tool

enum NodePoint {
	# 0 - General.

	# Core/root nodes.
	EDITOR_MAIN_WINDOW = 1,
	EDITOR_NODE = 100,
	EDITOR_FILE_SYSTEM,
	EDITOR_EXPORT,

	# Editor layout.
	LAYOUT_ROOT = 1_000,
	LAYOUT_TITLE_BAR,

	LAYOUT_DOCK_LEFT_LEFT_TOP,
	LAYOUT_DOCK_LEFT_LEFT_BOTTOM,
	LAYOUT_DOCK_LEFT_RIGHT_TOP,
	LAYOUT_DOCK_LEFT_RIGHT_BOTTOM,
	LAYOUT_DOCK_RIGHT_LEFT_TOP,
	LAYOUT_DOCK_RIGHT_LEFT_BOTTOM,
	LAYOUT_DOCK_RIGHT_RIGHT_TOP,
	LAYOUT_DOCK_RIGHT_RIGHT_BOTTOM,
	LAYOUT_DOCK_MIDDLE_BOTTOM,

	LAYOUT_DOCK_HIDDEN_CONTAINER,

	LAYOUT_DISTRACTION_FREE_BUTTON,

	# Misc editor nodes.
	RENDERING_MODE_BUTTON = 2_001,
	RENDERING_MODE_POPUP,

	# Editor menu bar.
	MENU_BAR = 10_000,
	MENU_BAR_SCENE_MENU,
	MENU_BAR_SCENE_OPEN_RECENT_MENU,
	MENU_BAR_SCENE_EXPORT_AS_MENU,
	MENU_BAR_PROJECT_MENU,
	MENU_BAR_PROJECT_TOOL_MENU,
	MENU_BAR_PROJECT_VERSION_CONTROL_MENU,
	MENU_BAR_DEBUG_MENU,
	MENU_BAR_EDITOR_MENU,
	MENU_BAR_EDITOR_DOCKS_MENU,
	MENU_BAR_EDITOR_LAYOUT_MENU,
	MENU_BAR_HELP_MENU,

	# Main editor view/screen.

	MAIN_VIEW_SWITCHER = 12_000,
	MAIN_VIEW_SWITCHER_2D_BUTTON,
	MAIN_VIEW_SWITCHER_3D_BUTTON,
	MAIN_VIEW_SWITCHER_SCRIPT_BUTTON,
	MAIN_VIEW_SWITCHER_GAME_BUTTON,
	MAIN_VIEW_SWITCHER_ASSET_LIB_BUTTON,

	MAIN_VIEW_CONTAINER = 13_000,
	MAIN_VIEW_CONTAINER_BOX,

	# Editor run bar.
	RUN_BAR = 14_000,
	RUN_BAR_PLAY_BUTTON,
	RUN_BAR_PAUSE_BUTTON,
	RUN_BAR_STOP_BUTTON,
	RUN_BAR_PLAY_CURRENT_BUTTON,
	RUN_BAR_PLAY_CUSTOM_BUTTON,
	RUN_BAR_MOVIE_MODE_BUTTON,

	# Scene tabs.
	SCENE_TABS = 15_000,
	SCENE_TABS_TAB_BAR,
	SCENE_TABS_ADD_BUTTON,

	# 100_000 - Dialogs.

	EDITOR_SETTINGS_DIALOG = 101_000,
	PROJECT_SETTINGS_DIALOG = 102_000,
	PROJECT_EXPORT_DIALOG = 103_000,
	EXPORT_TEMPLATE_MANAGER = 104_000,
	FEATURE_PROFILE_MANAGER = 105_000,
	BUILD_PROFILE_MANAGER = 106_000,
	EDITOR_ABOUT_DIALOG = 107_000,

	ORPHAN_RESOURCES_DIALOG = 108_000,
	DEPENDENCY_ERROR_DIALOG = 109_000,

	FBX_IMPORTER_MANAGER = 140_000,
	IMPORT_SCENE_SETTINGS_DIALOG = 150_000,
	IMPORT_AUDIO_STREAM_SETTINGS_DIALOG = 151_000,
	IMPORT_DYNAMIC_FONT_SETTINGS_DIALOG = 152_000,

	# 200_000 - Docks (including bottom panel).

	FILE_SYSTEM_DOCK = 201_000,
	GROUPS_DOCK = 203_000,
	HISTORY_DOCK = 205_000,
	IMPORT_DOCK = 207_000,

	INSPECTOR_DOCK = 209_000,

	INSPECTOR_DOCK_INSPECTOR,
	INSPECTOR_DOCK_INSPECTOR_BEGIN_BOX,
	INSPECTOR_DOCK_INSPECTOR_FAVORITES,
	INSPECTOR_DOCK_INSPECTOR_PROPERTIES,

	SCENE_DOCK = 211_000,

	SCENE_TREE_EDITOR,
	SCENE_TREE_EDITOR_TREE,

	SIGNALS_DOCK = 213_000,

	OUTPUT_DOCK = 215_000,
	DEBUGGER_DOCK = 217_000,

	ANIMATION_DOCK = 219_000,
	ANIMATION_TREE_DOCK = 221_000,
	AUDIO_DOCK = 223_000,
	GRID_MAP_DOCK = 225_000,
	POLYGON_DOCK = 227_000,
	REPLICATION_DOCK = 229_000,
	RESOURCE_PRELOADER_DOCK = 231_000,
	SEARCH_RESULTS_DOCK = 233_000,
	SHADER_DOCK = 235_000,
	SPRITE_FRAMES_DOCK = 237_000,
	THEME_DOCK = 239_000,
	TILE_MAP_DOCK = 241_000,
	TILE_SET_DOCK = 243_000,

	# 1_000_000 - Canvas editor.

	CANVAS_ITEM_EDITOR = 1_000_001,
	CANVAS_ITEM_EDITOR_VIEWPORT,

	CANVAS_ITEM_EDITOR_MAIN_TOOLBAR = 1_001_000,
	CANVAS_ITEM_EDITOR_MAIN_TOOLBAR_SELECT_BUTTON,
	CANVAS_ITEM_EDITOR_MAIN_TOOLBAR_MOVE_BUTTON,
	CANVAS_ITEM_EDITOR_MAIN_TOOLBAR_ROTATE_BUTTON,
	CANVAS_ITEM_EDITOR_MAIN_TOOLBAR_SCALE_BUTTON,
	CANVAS_ITEM_EDITOR_MAIN_TOOLBAR_SELECTABLE_BUTTON,
	CANVAS_ITEM_EDITOR_MAIN_TOOLBAR_PIVOT_BUTTON,
	CANVAS_ITEM_EDITOR_MAIN_TOOLBAR_PAN_BUTTON,
	CANVAS_ITEM_EDITOR_MAIN_TOOLBAR_RULER_BUTTON,
	CANVAS_ITEM_EDITOR_MAIN_TOOLBAR_LOCAL_SPACE_BUTTON,
	CANVAS_ITEM_EDITOR_MAIN_TOOLBAR_SMART_SNAP_BUTTON,
	CANVAS_ITEM_EDITOR_MAIN_TOOLBAR_GRID_BUTTON,
	CANVAS_ITEM_EDITOR_MAIN_TOOLBAR_SNAP_OPTIONS_BUTTON,
	CANVAS_ITEM_EDITOR_MAIN_TOOLBAR_LOCK_BUTTON,
	CANVAS_ITEM_EDITOR_MAIN_TOOLBAR_UNLOCK_BUTTON,
	CANVAS_ITEM_EDITOR_MAIN_TOOLBAR_GROUP_BUTTON,
	CANVAS_ITEM_EDITOR_MAIN_TOOLBAR_UNGROUP_BUTTON,
	CANVAS_ITEM_EDITOR_MAIN_TOOLBAR_SKELETON_OPTIONS_BUTTON,
	CANVAS_ITEM_EDITOR_MAIN_TOOLBAR_VIEW_OPTIONS_BUTTON,

	CANVAS_ITEM_EDITOR_CONTEXTUAL_TOOLBAR,

	# 2_000_000 - Spatial editor.


	# 3_000_000 - Script editor.


	# 4_000_000 - Game view.


	# 5_000_000 - Asset library.
}


# Utilities.

static var _node_point_name_map: Dictionary[int, String] = {}


static func _static_init() -> void:
	_node_point_name_map.clear()

	for key: String in NodePoint:
		var value: int = NodePoint[key]
		_node_point_name_map[value] = key.to_pascal_case()


static func get_node_point_name(value: int) -> String:
	if not _node_point_name_map.has(value):
		return ""

	return _node_point_name_map[value]
