## Enums used by the editor interface access system.
@tool

enum NodePoint {
	#region 0 - General.

	# Core/root nodes.
	EDITOR_MAIN_WINDOW = 1,
	EDITOR_NODE = 100,
	EDITOR_FILE_SYSTEM,
	EDITOR_EXPORT,

	# Editor layout.
	LAYOUT_ROOT = 1_000,
	LAYOUT_TITLE_BAR,

	LAYOUT_DOCK_LEFT_LEFT_TOP = 1_101,
	LAYOUT_DOCK_LEFT_LEFT_BOTTOM,
	LAYOUT_DOCK_LEFT_RIGHT_TOP,
	LAYOUT_DOCK_LEFT_RIGHT_BOTTOM,
	LAYOUT_DOCK_RIGHT_LEFT_TOP,
	LAYOUT_DOCK_RIGHT_LEFT_BOTTOM,
	LAYOUT_DOCK_RIGHT_RIGHT_TOP,
	LAYOUT_DOCK_RIGHT_RIGHT_BOTTOM,
	LAYOUT_DOCK_MIDDLE_BOTTOM,
	LAYOUT_DOCK_HIDDEN_CONTAINER,

	LAYOUT_DISTRACTION_FREE_BUTTON = 2_001,

	# Editor menu bar.
	MENU_BAR = 10_000,
	MENU_BAR_SCENE_MENU,
	MENU_BAR_SCENE_OPEN_RECENT_MENU,
	MENU_BAR_SCENE_EXPORT_AS_MENU,
	MENU_BAR_PROJECT_MENU,
	MENU_BAR_PROJECT_TOOL_MENU,
	MENU_BAR_PROJECT_VERSION_CONTROL_MENU,
	MENU_BAR_DEBUG_MENU,
	MENU_BAR_EDITOR_MENU,
	MENU_BAR_EDITOR_DOCKS_MENU,
	MENU_BAR_EDITOR_LAYOUT_MENU,
	MENU_BAR_HELP_MENU,

	# Main editor view/screen.

	MAIN_VIEW_SWITCHER = 12_000,
	MAIN_VIEW_SWITCHER_2D_BUTTON,
	MAIN_VIEW_SWITCHER_3D_BUTTON,
	MAIN_VIEW_SWITCHER_SCRIPT_BUTTON,
	MAIN_VIEW_SWITCHER_GAME_BUTTON,
	MAIN_VIEW_SWITCHER_ASSET_LIB_BUTTON,

	MAIN_VIEW_CONTAINER = 13_000,
	MAIN_VIEW_CONTAINER_BOX,

	# Editor run bar.
	RUN_BAR = 14_000,
	RUN_BAR_PLAY_BUTTON,
	RUN_BAR_PAUSE_BUTTON,
	RUN_BAR_STOP_BUTTON,
	RUN_BAR_PLAY_CURRENT_BUTTON,
	RUN_BAR_PLAY_CUSTOM_BUTTON,
	RUN_BAR_MOVIE_MODE_BUTTON,

	# Extra title bar elements.
	RENDERING_MODE_BUTTON = 15_001,
	EDITOR_UPDATE_SPINNER,

	# Scene tabs.
	SCENE_TABS = 16_000,
	SCENE_TABS_TAB_BAR,
	SCENE_TABS_ADD_BUTTON,
	SCENE_TABS_LIST_BUTTON,

	#endregion

	# 100_000 - Dialogs.

	EDITOR_SETTINGS_DIALOG = 101_000,
	PROJECT_SETTINGS_DIALOG = 102_000,
	PROJECT_EXPORT_DIALOG = 103_000,
	EXPORT_TEMPLATE_MANAGER = 104_000,
	FEATURE_PROFILE_MANAGER = 105_000,
	BUILD_PROFILE_MANAGER = 106_000,
	EDITOR_ABOUT_DIALOG = 107_000,

	ORPHAN_RESOURCES_DIALOG = 108_000,
	DEPENDENCY_ERROR_DIALOG = 109_000,

	FBX_IMPORTER_MANAGER = 140_000,
	IMPORT_SCENE_SETTINGS_DIALOG = 150_000,
	IMPORT_AUDIO_STREAM_SETTINGS_DIALOG = 151_000,
	IMPORT_DYNAMIC_FONT_SETTINGS_DIALOG = 152_000,


	# 200_000 - Docks (including bottom panel).

	# Docks: ...

	FILE_SYSTEM_DOCK = 201_000,
	HISTORY_DOCK = 203_000,
	IMPORT_DOCK = 205_000,

	#region Docks: Inspector.

	INSPECTOR_DOCK = 210_000,
	INSPECTOR_DOCK_INSPECTOR,
	INSPECTOR_DOCK_INSPECTOR_BEGIN_BOX,
	INSPECTOR_DOCK_INSPECTOR_FAVORITES,
	INSPECTOR_DOCK_INSPECTOR_PROPERTIES,

	#endregion

	#region Docks: Scene.

	SCENE_DOCK = 220_000,
	SCENE_TREE_EDITOR,
	SCENE_TREE_EDITOR_TREE,

	#endregion

	# Docks: ...

	GROUPS_DOCK = 230_000,
	SIGNALS_DOCK = 240_000,

	# Docks: ...

	OUTPUT_DOCK = 300_000,
	DEBUGGER_DOCK = 310_000,

	ANIMATION_DOCK = 400_000,
	ANIMATION_TREE_DOCK = 410_000,
	AUDIO_DOCK = 420_000,

	#region Docks: GridMap.

	GRID_MAP_DOCK = 430_000,
	GRID_MAP_EDITOR,

	#endregion

	#region Docks: Polygon.

	POLYGON_DOCK = 440_000,

	#endregion

	#region Docks: Replication.

	REPLICATION_DOCK = 450_000,
	REPLICATION_EDITOR,

	#endregion

	# Docks: ...

	RESOURCE_PRELOADER_DOCK = 460_000,
	SEARCH_RESULTS_DOCK = 470_000,
	SHADER_DOCK = 480_000,
	SHADER_FILE_DOCK = 490_000,

	#region Docks: SpriteFrames.

	SPRITE_FRAMES_DOCK = 500_000,

	#endregion

	#region Docks: Theme.

	THEME_DOCK = 510_000,

	#endregion

	#region Docks: TileMap.

	TILE_MAP_DOCK = 520_000,
	TILE_MAP_DOCK_TABS,

	TILE_MAP_COMMON_TOOLBAR_PREVIOUS_BUTTON = 520_101,
	TILE_MAP_COMMON_TOOLBAR_NEXT_BUTTON,
	TILE_MAP_COMMON_TOOLBAR_SELECT_LAYER_BUTTON,
	TILE_MAP_COMMON_TOOLBAR_SELECT_ALL_BUTTON,
	TILE_MAP_COMMON_TOOLBAR_HIGHLIGHT_BUTTON,
	TILE_MAP_COMMON_TOOLBAR_GRID_BUTTON,
	TILE_MAP_COMMON_TOOLBAR_MENU_BUTTON,

	TILE_MAP_TILES_PANEL = 520_200,
	TILE_MAP_TILES_TOOLBAR_SELECT_BUTTON,
	TILE_MAP_TILES_TOOLBAR_PAINT_BUTTON,
	TILE_MAP_TILES_TOOLBAR_LINE_BUTTON,
	TILE_MAP_TILES_TOOLBAR_RECT_BUTTON,
	TILE_MAP_TILES_TOOLBAR_BUCKET_BUTTON,
	TILE_MAP_TILES_TOOLBAR_PICKER_BUTTON,
	TILE_MAP_TILES_TOOLBAR_ERASER_BUTTON,
	TILE_MAP_TILES_TOOLBAR_ROTATE_LEFT_BUTTON,
	TILE_MAP_TILES_TOOLBAR_ROTATE_RIGHT_BUTTON,
	TILE_MAP_TILES_TOOLBAR_FLIP_H_BUTTON,
	TILE_MAP_TILES_TOOLBAR_FLIP_V_BUTTON,
	TILE_MAP_TILES_TOOLBAR_CONTIGUOUS_BUTTON,
	TILE_MAP_TILES_TOOLBAR_RANDOM_BUTTON,

	TILE_MAP_TILES_SOURCES_LIST = 520_300,
	TILE_MAP_TILES_SOURCES_LIST_SORT_BUTTON,

	TILE_MAP_TILES_ATLAS_VIEW = 520_400,
	TILE_MAP_TILES_ATLAS_VIEW_ZOOM_WIDGET,
	TILE_MAP_TILES_ATLAS_VIEW_CENTER_BUTTON,

	TILE_MAP_TILES_SCENES_LIST = 520_500,

	TILE_MAP_PATTERNS_PANEL = 520_600,
	TILE_MAP_PATTERNS_LIST,

	TILE_MAP_TERRAINS_PANEL = 520_700,
	TILE_MAP_TERRAINS_TOOLBAR_PAINT_BUTTON,
	TILE_MAP_TERRAINS_TOOLBAR_LINE_BUTTON,
	TILE_MAP_TERRAINS_TOOLBAR_RECT_BUTTON,
	TILE_MAP_TERRAINS_TOOLBAR_BUCKET_BUTTON,
	TILE_MAP_TERRAINS_TOOLBAR_PICKER_BUTTON,
	TILE_MAP_TERRAINS_TOOLBAR_ERASER_BUTTON,
	TILE_MAP_TERRAINS_TOOLBAR_CONTIGUOUS_BUTTON,

	TILE_MAP_TERRAINS_SETS_LIST = 520_800,
	TILE_MAP_TERRAINS_TILES_LIST = 520_900,

	#endregion

	#region Docks: TileSet.

	TILE_SET_DOCK = 530_000,
	TILE_SET_DOCK_TABS,

	TILE_SET_TILES_PANEL = 530_100,

	TILE_SET_TILES_SOURCES_LIST = 530_200,
	TILE_SET_TILES_SOURCES_LIST_BUTTONS,
	TILE_SET_TILES_SOURCES_LIST_DELETE_BUTTON,
	TILE_SET_TILES_SOURCES_LIST_ADD_BUTTON,
	TILE_SET_TILES_SOURCES_LIST_MENU_BUTTON,
	TILE_SET_TILES_SOURCES_LIST_SORT_BUTTON,

	TILE_SET_TILES_ATLAS_EDITOR = 530_300,
	TILE_SET_TILES_ATLAS_EDITOR_TABS,
	TILE_SET_TILES_ATLAS_EDITOR_SETUP_BUTTON,
	TILE_SET_TILES_ATLAS_EDITOR_SELECT_BUTTON,
	TILE_SET_TILES_ATLAS_EDITOR_PAINT_BUTTON,

	TILE_SET_TILES_ATLAS_EDITOR_SETUP_PANEL = 530_400,
	TILE_SET_TILES_ATLAS_EDITOR_SELECT_PANEL = 530_500,
	TILE_SET_TILES_ATLAS_EDITOR_PAINT_PANEL = 530_600,

	TILE_SET_TILES_ATLAS_EDITOR_TOOLBARS = 530_700,
	TILE_SET_TILES_ATLAS_EDITOR_SETUP_TOOLBAR_ERASE_BUTTON,
	TILE_SET_TILES_ATLAS_EDITOR_SETUP_TOOLBAR_MENU_BUTTON,
	TILE_SET_TILES_ATLAS_EDITOR_PAINT_TOOLBARS,

	TILE_SET_TILES_ATLAS_EDITOR_ATLAS_VIEW = 530_800,
	TILE_SET_TILES_ATLAS_EDITOR_ATLAS_VIEW_ZOOM_WIDGET,
	TILE_SET_TILES_ATLAS_EDITOR_ATLAS_VIEW_CENTER_BUTTON,

	TILE_SET_TILES_SCENES_COLLECTION_EDITOR = 530_900,

	TILE_SET_TILES_SCENES_COLLECTION_EDITOR_PROPERTIES = 531_000,
	TILE_SET_TILES_SCENES_COLLECTION_EDITOR_PROPERTIES_SCENE,
	TILE_SET_TILES_SCENES_COLLECTION_EDITOR_PROPERTIES_TILE,

	TILE_SET_TILES_SCENES_COLLECTION_EDITOR_SCENES = 531_100,
	TILE_SET_TILES_SCENES_COLLECTION_EDITOR_SCENES_LIST,
	TILE_SET_TILES_SCENES_COLLECTION_EDITOR_SCENES_BUTTONS,
	TILE_SET_TILES_SCENES_COLLECTION_EDITOR_SCENES_ADD_BUTTON,
	TILE_SET_TILES_SCENES_COLLECTION_EDITOR_SCENES_DELETE_BUTTON,

	TILE_SET_PATTERNS_PANEL = 531_200,
	TILE_SET_PATTERNS_LIST,

	TILE_SET_ATLAS_MERGING_DIALOG = 531_300,
	TILE_SET_TILE_PROXIES_MANAGER = 531_400,

	#endregion


	#region 1_000_000 - Canvas editor.

	CANVAS_ITEM_EDITOR = 1_000_001,

	CANVAS_ITEM_EDITOR_MAIN_TOOLBAR = 1_001_000,
	CANVAS_ITEM_EDITOR_MAIN_TOOLBAR_SELECT_BUTTON,
	CANVAS_ITEM_EDITOR_MAIN_TOOLBAR_MOVE_BUTTON,
	CANVAS_ITEM_EDITOR_MAIN_TOOLBAR_ROTATE_BUTTON,
	CANVAS_ITEM_EDITOR_MAIN_TOOLBAR_SCALE_BUTTON,
	CANVAS_ITEM_EDITOR_MAIN_TOOLBAR_SELECTABLE_BUTTON,
	CANVAS_ITEM_EDITOR_MAIN_TOOLBAR_PIVOT_BUTTON,
	CANVAS_ITEM_EDITOR_MAIN_TOOLBAR_PAN_BUTTON,
	CANVAS_ITEM_EDITOR_MAIN_TOOLBAR_RULER_BUTTON,
	CANVAS_ITEM_EDITOR_MAIN_TOOLBAR_LOCAL_SPACE_BUTTON,
	CANVAS_ITEM_EDITOR_MAIN_TOOLBAR_SMART_SNAP_BUTTON,
	CANVAS_ITEM_EDITOR_MAIN_TOOLBAR_GRID_BUTTON,
	CANVAS_ITEM_EDITOR_MAIN_TOOLBAR_SNAP_OPTIONS_BUTTON,
	CANVAS_ITEM_EDITOR_MAIN_TOOLBAR_LOCK_BUTTON,
	CANVAS_ITEM_EDITOR_MAIN_TOOLBAR_UNLOCK_BUTTON,
	CANVAS_ITEM_EDITOR_MAIN_TOOLBAR_GROUP_BUTTON,
	CANVAS_ITEM_EDITOR_MAIN_TOOLBAR_UNGROUP_BUTTON,
	CANVAS_ITEM_EDITOR_MAIN_TOOLBAR_SKELETON_OPTIONS_BUTTON,
	CANVAS_ITEM_EDITOR_MAIN_TOOLBAR_VIEW_OPTIONS_BUTTON,

	CANVAS_ITEM_EDITOR_CONTEXTUAL_TOOLBARS = 1_002_000,

	CANVAS_ITEM_EDITOR_VIEWPORT = 1_100_001,
	CANVAS_ITEM_EDITOR_VIEWPORT_SCENE_ROOT,
	CANVAS_ITEM_EDITOR_VIEWPORT_OVERLAYS,

	#endregion

	#region 2_000_000 - Spatial editor.

	NODE_3D_EDITOR = 2_000_001,
	NODE_3D_EDITOR_VIEWPORTS,

	NODE_3D_EDITOR_MAIN_TOOLBAR = 2_001_000,
	NODE_3D_EDITOR_CONTEXTUAL_TOOLBARS = 2_002_000,

	#NODE_3D_EDITOR_VIEWPORT = 2_100_000,
	NODE_3D_EDITOR_VIEWPORT_SCENE_ROOT = 2_100_001,
	NODE_3D_EDITOR_VIEWPORT_OVERLAYS,

	#endregion

	#region 3_000_000 - Script editor.

	SCRIPT_EDITOR = 3_000_001,

	SCRIPT_EDITOR_TOOLBAR = 3_001_000,
	SCRIPT_EDITOR_TOOLBAR_FILE_MENU_BUTTON,
	SCRIPT_EDITOR_TOOLBAR_SEARCH_MENU_BUTTON,
	SCRIPT_EDITOR_TOOLBAR_DEBUG_MENU_BUTTON,
	SCRIPT_EDITOR_TOOLBAR_CURRENT_LABEL,
	SCRIPT_EDITOR_TOOLBAR_ONLINE_DOCS_BUTTON,
	SCRIPT_EDITOR_TOOLBAR_SEARCH_HELP_BUTTON,
	SCRIPT_EDITOR_TOOLBAR_NAVIGATE_BACK_BUTTON,
	SCRIPT_EDITOR_TOOLBAR_NAVIGATE_FORWARD_BUTTON,
	SCRIPT_EDITOR_TOOLBAR_MAKE_FLOATING_BUTTON,

	SCRIPT_EDITOR_SIDEBAR = 3_002_000,
	SCRIPT_EDITOR_SCRIPT_LIST,
	SCRIPT_EDITOR_SCRIPT_LIST_FILTER,
	SCRIPT_EDITOR_CURRENT_SCRIPT_INDEX,
	SCRIPT_EDITOR_CURRENT_SCRIPT_INDEX_FILTER,
	SCRIPT_EDITOR_CURRENT_SCRIPT_INDEX_SORT_BUTTON,
	SCRIPT_EDITOR_CURRENT_DOCS_INDEX,

	SCRIPT_EDITOR_CONTAINER = 3_003_000,
	SCRIPT_EDITOR_CONTAINER_TABS,
	SCRIPT_EDITOR_CONTAINER_FIND_REPLACE_BAR,

	#endregion

	#region 4_000_000 - Game view.

	GAME_VIEW = 4_000_001,

	#endregion

	#region 5_000_000 - Asset library.

	ASSET_LIBRARY = 5_000_001,

	#endregion


	#region 100_000_000 - Reusable components.

	# These nodes are reused multiple times throughout the editor UI,
	# e.g. one ScriptTextEditor per open script, or various inspector
	# panels. In some cases they cannot be fetched via static node points
	# at all, like in the case of script editors, though some may be
	# accessible via points defined above.
	#
	# The definitions below exist for fetching children/descendants of
	# these nodes and expect a known base reference. See EIA.get_node_relative().

	#SCRIPT_TEXT_EDITOR = 100_001_000,
	SCRIPT_TEXT_EDITOR_CODE_EDITOR = 100_001_001,
	SCRIPT_TEXT_EDITOR_CODE_EDITOR_CODE_EDIT,
	SCRIPT_TEXT_EDITOR_CODE_EDITOR_FOOTER_BAR,

	#TEXT_EDITOR = 100_002_000,
	TEXT_EDITOR_CODE_EDITOR = 100_002_001,
	TEXT_EDITOR_CODE_EDITOR_CODE_EDIT,
	TEXT_EDITOR_CODE_EDITOR_FOOTER_BAR,

	#EDITOR_HELP = 100_003_000,
	EDITOR_HELP_RICH_TEXT = 100_003_001,
	EDITOR_HELP_FIND_BAR,
	EDITOR_HELP_FOOTER_BAR,
	EDITOR_HELP_FOOTER_SIDEBAR_BUTTON,

	#EDITOR_ZOOM_WIDGET = 100_004_000,
	EDITOR_ZOOM_WIDGET_ZOOM_OUT_BUTTON = 100_004_001,
	EDITOR_ZOOM_WIDGET_ZOOM_IN_BUTTON,
	EDITOR_ZOOM_WIDGET_RESET_BUTTON,

	#endregion
}


# Utilities.

static var _node_point_name_map: Dictionary[int, String] = {}


static func _static_init() -> void:
	_node_point_name_map.clear()

	for key: String in NodePoint:
		var value: int = NodePoint[key]
		_node_point_name_map[value] = key.to_pascal_case()


static func get_node_point_name(value: int) -> String:
	if not _node_point_name_map.has(value):
		return ""

	return _node_point_name_map[value]
